services:
  metatool-web:
    container_name: metatool-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '12005:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=metatool-postgres
      - DB_PORT=5432
      - DB_NAME=metatool
      - DB_USER=metatool
      - DB_PASSWORD=m3t4t00l
    depends_on:
      - metatool-postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  metatool-postgres:
    container_name: metatool-postgres
    image: postgres:16.2-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: metatool
      POSTGRES_USER: metatool
      POSTGRES_PASSWORD: m3t4t00l
    ports:
      - '8432:5432'
    volumes:
      - metatool-postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U metatool" ]
      interval: 5s
      timeout: 5s
      retries: 5

  drizzle-migrate:
    container_name: drizzle-migrate
    build:
      context: .
      dockerfile: Dockerfile
      target: migrator
    command: pnpm drizzle-kit migrate
    environment:
      - DB_HOST=metatool-postgres
      - DB_PORT=5432
      - DB_NAME=metatool
      - DB_USER=metatool
      - DB_PASSWORD=m3t4t00l
    depends_on:
      metatool-postgres:
        condition: service_healthy

volumes:
  metatool-postgres:
    driver: local
